language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features="num bit-vec"
  - cargo doc --features="num bit-vec"
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ssh-agent .travis/deploy.sh
notifications:
  email:
    on_success: never
