language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
after_success: |
  echo $TRAVIS_BRANCH &&
  echo $TRAVIS_PULL_REQUEST &&
  echo $TRAVIS_RUST_VERSION &&
  [ $TRAVIS_BRANCH = travis ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  ssh-agent .travis/deploy.sh
notifications:
  email:
    on_success: never
