[package]
name = "yasna"
version = "0.1.0"
authors = ["Masaki Hara <ackie.h.gmai@gmail.com>"]

description = "ASN.1 library for Rust"
documentation = "https://qnighy.github.io/yasna.rs"
homepage = "https://github.com/qnighy/yasna.rs"
repository = "https://github.com/qnighy/yasna.rs.git"
readme = "README.md"
keywords = ["parser", "serialization"]
license = "MIT/Apache-2.0"

[dependencies]
num = "0.1.32"
